<a href="https://colab.research.google.com/github/Dingcyber/Studymaterials/blob/main/Linear_Algebra_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy（Numerical Python）



## 数组（arrays）

---


* 数组：多维数组对象｜`ndarry`（n-dimentional-array）
  * 一个数组内的对象只能是单一类型：浮点数float｜整数int｜字符串char
* 创建数组
  * `np.array()`: 输入一个列表，返回一个一维数组
  * `np.arange(start,stop,step)`: 返回给定区间内的等距均分的数组｜左闭右开｜start默认为0｜step默认为0
  * `np.linspace(start,stop,num,dtype=)`: 返回定区间内的一个等数均分的数组｜左闭右闭｜num默认是5｜默认类型是浮点数float
  * `np.ones(num)`: 返回一个包含num个1的数组
  * `np.zeros(num)`: 返回一个包含num个0的数组
  * `np.empty(num)`: 返回一个包含num个未初始化元素的数组
  * `np.random.rand(num)`: 返回一个包含num个随机数的数组
  * `np.reshape(一维数组,（a,b）)`: 将一维数组重塑为a行b列数组
* 数组属性（attributes）
  * `ndarray.ndim`: 返回数组的维度｜维数（dimension），描述数组所具有的维度的数量，也就是数组的秩（rank）
  * `ndarray.shape`: 返回数组的形状｜维度大小（shape），描述数组每个维度上的大小，用一个元组表示，如(3,4)表示一个3行4列的数组
  * `ndarray.size`: 返回数组的大小｜元素总数，指的是数组中所有元素的总个数
* 数组运算
  * `+｜-｜*｜/`: 加减乘除，对应项相加减乘除
  * `ndarray * c`: 标乘，将标量c广播到（broadcasting）数组中的每一个元素
* 数组操作
  * `[]`: 索引，从数组中选择特定的元素或整个行或列或平面
  * `_[start:end:step]`: 切片,提取多维数组中的行｜左闭右开｜start默认为0｜end默认为倒数第一个｜step默认为1
  * `[:,列索引]`：切片，提取多维数组中的单列
  * `[:,开始列：结束列]`：切片，提取多维数组中的连续多列
  * `[:,[列索引1，列索引2,...]`: 切片，提取多维数组中的不连续多列
  * `np.vstack()`: 垂直堆叠（stacking）数组，沿第一个维度，即行方向
  * `np.hstack()`: 水平堆叠数组，沿第二个维度，即列方向
  * `no.hsplit()`: 将数组分解为小数组

In [ ]:
import numpy as np

### 创建一维数组
---



In [ ]:
# 创建一个包含1，2，3的数组
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
# 创建字符串数组
char_arr = np.array(["Welcome to Math for ML!"])
print(char_arr)
print(char_arr.dtype) #<U23的意思是这个字符串是小端架构上的23个字符unicode字符串

['Welcome to Math for ML!']
<U23


In [ ]:
# 创建一个从0开始包含3个整数的数组
b = np.arange(3)
print(b)

[0 1 2]


In [ ]:
# 创建一个从0开始包含3个整数的数组,指定类型为float
b = np.arange(3, dtype = float)
print(b)

[0. 1. 2.]


In [ ]:
# 创建一个从1到20每个数相差3的数组
c = np.arange(1, 20, 3)
print(c)
print(c.dtype)

[ 1  4  7 10 13 16 19]
int64


In [ ]:
# 创建一个从1到20每个数相差3的数组,指定类型为int
c = np.arange(1, 20, 3, dtype = int)
print(c)
print(c.dtype)

[ 1  4  7 10 13 16 19]
int64


In [ ]:
# 创建一个0到100的包含五个数的均分数组
lin_spaced_arr = np.linspace(0,100,5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


In [ ]:
# 创建一个0到100的包含五个数的均分数组,指定类型为整数int
lin_spaced_arr_int = np.linspace(0,100,5,dtype=int)
print(lin_spaced_arr_int)

[  0  25  50  75 100]


In [ ]:
# 创建一个包含3个1的数组
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [ ]:
# 创建一个包含3个0的数组
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [ ]:
# 创建一个包含3个未初始化元素的数组
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [ ]:
# 创建一个包含3个随机数的数组
rand_arr = np.random.rand(3)
print(rand_arr)

[0.42755184 0.7383775  0.24565752]


### 创建二维数组
---




In [ ]:
# 创建一个二维数组
two_dim_arr = np.array([[1,2,3], [4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 将一维数组重塑为二维数组
one_dim_arr = np.array([1,2,3,4,5,6])
print(one_dim_arr)
multi_dim_arr = np.reshape(one_dim_arr,(2,3)) #将一维数组重塑为一个2x3数组
print(multi_dim_arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


### 查看数组属性
---



In [ ]:
multi_dim_arr.ndim

2

In [ ]:
multi_dim_arr.shape

(2, 3)

In [ ]:
multi_dim_arr.size

6

### 数组运算
---



In [ ]:
arr_1 = np.array([2,4,6])
arr_2 = np.array([1,3,5])

# 加法
addition = arr_1 + arr_2
print(addition)

# 减法
substraction = arr_1 - arr_2
print(substraction)

# 乘法
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


In [ ]:
# 向量标乘
vector = np.array([1,2])
vector * 1.6

array([1.6, 3.2])

### 数组操作
---



In [ ]:
# 索引一维数组中的元素
a_op = ([1,2,3,4,5])
print(a_op[2])
print(a_op[0])

3
1


In [ ]:
# 索引多维数组中的元素
two_dim_op = np.array(([1,2,3],
                       [4,5,6],
                       [7,8,9]))
print(two_dim_op[1])
print(two_dim_op[2][1])

[4 5 6]
8


In [ ]:
# 切片,step用默认值
sliced_arr1 = a_op[1:4]
print(sliced_arr1)

[2, 3, 4]


In [ ]:
# 切片，start和step用默认值
sliced_arr2 = a_op[:3]
print(sliced_arr2)

[1, 2, 3]


In [ ]:
# 切片，end和step用默认值
sliced_arr3 = a_op[2:]
print(sliced_arr3)

[3, 4, 5]


In [ ]:
# 切片，start和end用默认值
sliced_arr4 = a_op[::2]
print(sliced_arr4)

[1, 3, 5]


In [ ]:
# 切片，start|end|step均用默认值
print(a_op == a_op[:] == a_op[::])

True


In [ ]:
# 切片，提取多维数组中的项,step用默认值
sliced_arr5 = two_dim_op[0:2]
print(sliced_arr5)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 切片，提取多维数组中的行，step用默认值
sliced_two_dim_rows = two_dim_op[1:3]
print(sliced_two_dim_rows)

[[4 5 6]
 [7 8 9]]


In [ ]:
# 切片，提取多维数组中的列
sliced_two_dim_cols = two_dim_op[:,1]
print(sliced_two_dim_cols)

[2 5 8]


In [ ]:
# 堆叠：创建原始数组
a1 = np.array([[1,1],
               [2,2]])
a2 = np.array([[3,3],
               [4,4]])
print(f"a1:\n{a1}")
print(f"a2:\n{a2}")

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [ ]:
# 堆叠，垂直堆叠数组
vert_stack = np.vstack((a1,a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [ ]:
# 堆叠，水平堆叠数组
horz_stack = np.hstack((a1,a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]
